service: api-emails

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-domain-manager

custom:
  domains:
    default: api-emails.${opt:stage, 'sandpit'}.cloud.spacenow.com
    prod: api-emails.spacenow.com
  certificates:
    default: ${ssm:/${opt:stageCert, 'SANDPIT'}/ACM_CERTIFICATE}
    prod: ${ssm:/${opt:stageCert, 'SANDPIT'}/SPACENOW/ACM_CERTIFICATE}
  customDomain:
    domainName: ${self:custom.domains.${opt:stage, 'sandpit'}, self:custom.domains.default}
    basePath: ""
    stage: ${opt:stage, 'sandpit'}
    certificateArn: ${self:custom.certificates.${opt:stage, 'sandpit'}, self:custom.certificates.default}
    createRoute53Record: true
    endpointType: "regional"

dotenv:
  path: ./.env
  basePath: ./
  include:
    - EMAIL
    - DOMAIN

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'sandpit'}
  region: ap-southeast-2
  environment:
    EMAIL: ${ssm:/${opt:stageCert, 'SANDPIT'}/SPACENOW/ADMIN_EMAIL, env:EMAIL}
    DOMAIN: ${env:DOMAIN}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendTemplatedEmail"
      Resource: "*"

functions:
  send:
    handler: src/email.send
    events:
      - http:
          path: email/send
          method: post
          cors: true

resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}
