service: api-emails

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-domain-manager
  - serverless-prune-plugin

custom:
  domains:
    default: api-emails.${opt:stage, 'sandpit'}.cloud.spacenow.com
    prod: api-emails.spacenow.com
  subnet:
    default:
      privateA: subnet-0c75bbd1ea60481d4
      privateB: subnet-070ac699acd775765
      privateC: subnet-0eca793083726120c
    prod:
      privateA: subnet-04d5af2458ebdabbf
      privateB: subnet-010ee1d571a9ca82c
      privateC: subnet-069abf1da82eb3acc
  securityGroup:
    default: sg-0dbf2b9d996f4c91e
    prod: sg-00b4a2172f7e29276
  customDomain:
    domainName: ${self:custom.domains.${opt:stage, 'sandpit'}, self:custom.domains.default}
    basePath: ""
    stage: ${opt:stage, 'sandpit'}
    certificateArn: ${ssm:/${opt:stageCert, 'SANDPIT'}/ACM_CERTIFICATE}
    createRoute53Record: true
    endpointType: "regional"
  prune:
    automatic: true
    number: 5

dotenv:
  path: ./.env
  basePath: ./
  include:
    - DOMAIN
    - ADMIN_EMAIL
    - DATABASE_SCHEMA
    - DATABASE_HOST
    - DATABASE_USERNAME
    - DATABASE_PASSWORD
    - API_BOOKING
    - NEW_LISTING_PROCESS_HOST

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'sandpit'}
  region: ap-southeast-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendTemplatedEmail"
      Resource: "*"
  vpc:
    securityGroupIds:
      - ${self:custom.securityGroup.${opt:stage, 'sandpit'}, self:custom.securityGroup.default}
    subnetIds:
      - ${self:custom.subnet.${opt:stage, 'sandpit'}.privateA, self:custom.subnet.default.privateA}
      - ${self:custom.subnet.${opt:stage, 'sandpit'}.privateB, self:custom.subnet.default.privateB}
      - ${self:custom.subnet.${opt:stage, 'sandpit'}.privateC, self:custom.subnet.default.privateC}
  environment:
    DOMAIN: ${env:DOMAIN}
    ADMIN_EMAIL: ${ssm:/${opt:stageCert, 'SANDPIT'}/SPACENOW/ADMIN_EMAIL~true}
    DATABASE_SCHEMA: ${ssm:/${opt:stageCert, 'SANDPIT'}/SPACENOW/DATABASE_SCHEMA~true}
    DATABASE_HOST: ${ssm:/${opt:stageCert, 'SANDPIT'}/SPACENOW/DATABASE_HOST~true}
    DATABASE_USERNAME: ${ssm:/${opt:stageCert, 'SANDPIT'}/SPACENOW/DATABASE_USER~true}
    DATABASE_PASSWORD: ${ssm:/${opt:stageCert, 'SANDPIT'}/SPACENOW/DATABASE_PASSWORD~true}
    API_BOOKING: ${ssm:/${opt:stageCert, 'SANDPIT'}/SPACENOW/API_BOOKING~true}
    NEW_LISTING_PROCESS_HOST: ${ssm:/${opt:stageCert, 'SANDPIT'}/SPACENOW/NEW_LISTING_PROCESS_HOST~true}

functions:
  send:
    handler: src/functions/sendEmailByTemplate.main
    events:
      - http:
          path: email/send
          method: post
          cors: true
  sendEmailByBookingInstantHost:
    handler: src/functions/sendEmailByBookingInstantHost.main
    events:
      - http:
          path: email/booking/{bookingId}/instant/host
          method: post
          cors: true
  sendEmailByBookingInstantGuest:
    handler: src/functions/sendEmailByBookingInstantGuest.main
    events:
      - http:
          path: email/booking/{bookingId}/instant/guest
          method: post
          cors: true
  sendEmailByBookingRequestHost:
    handler: src/functions/sendEmailByBookingRequestHost.main
    events:
      - http:
          path: email/booking/{bookingId}/request/host
          method: post
          cors: true
  sendEmailByBookingRequestGuest:
    handler: src/functions/sendEmailByBookingRequestGuest.main
    events:
      - http:
          path: email/booking/{bookingId}/request/guest
          method: post
          cors: true
  sendEmailByBookingDeclined:
    handler: src/functions/sendEmailByBookingDeclined.main
    events:
      - http:
          path: email/booking/{bookingId}/declined
          method: post
          cors: true

resources:
  - ${file(src/resources/api-gateway-errors.yml)}
