service: api-emails

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-domain-manager
  - serverless-prune-plugin

custom:
  domains:
    default: api-emails.${opt:stage, 'sandpit'}.cloud.spacenow.com
    prod: api-emails.spacenow.com
  customDomain:
    domainName: ${self:custom.domains.${opt:stage, 'sandpit'}, self:custom.domains.default}
    basePath: ''
    stage: ${opt:stage, 'sandpit'}
    certificateArn: ${ssm:/${opt:stageCert, 'SANDPIT'}/ACM_CERTIFICATE}
    createRoute53Record: true
    endpointType: 'regional'
  prune:
    automatic: true
    number: 5

dotenv:
  path: ./.env
  basePath: ./
  include:
    - EMAIL
    - DOMAIN
    - DATABASE_SCHEMA
    - DATABASE_HOST
    - DATABASE_USERNAME
    - DATABASE_PASSWORD
    - API_BOOKING
    - NEW_LISTING_PROCESS_HOST

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'sandpit'}
  region: ap-southeast-2
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'ses:SendTemplatedEmail'
      Resource: '*'
  vpc:
    securityGroupIds:
      - sg-0dbf2b9d996f4c91e
    subnetIds:
      - subnet-0c75bbd1ea60481d4
      - subnet-070ac699acd775765
      - subnet-0eca793083726120c
  environment:
    EMAIL: ${ssm:/${opt:stageCert, 'SANDPIT'}/SPACENOW/ADMIN_EMAIL, env:EMAIL}
    DOMAIN: ${env:DOMAIN}
    DATABASE_SCHEMA: ${ssm:/${opt:stageCert, 'SANDPIT'}/SPACENOW/DATABASE_SCHEMA~true}
    DATABASE_HOST: ${ssm:/${opt:stageCert, 'SANDPIT'}/SPACENOW/DATABASE_HOST~true}
    DATABASE_USERNAME: ${ssm:/${opt:stageCert, 'SANDPIT'}/SPACENOW/DATABASE_USER~true}
    DATABASE_PASSWORD: ${ssm:/${opt:stageCert, 'SANDPIT'}/SPACENOW/DATABASE_PASSWORD~true}
    API_BOOKING: ${ssm:/${opt:stageCert, 'SANDPIT'}/SPACENOW/API_BOOKING~true}
    NEW_LISTING_PROCESS_HOST: ${ssm:/${opt:stageCert, 'SANDPIT'}/SPACENOW/NEW_LISTING_PROCESS_HOST~true}

functions:
  send:
    handler: src/functions/sendEmailByTemplate.main
    events:
      - http:
          path: email/send
          method: post
          cors: true
  sendEmailByBookingInstantHost:
    handler: src/functions/sendEmailByBookingInstantHost.main
    events:
      - http:
          path: email/booking/{bookingId}/instant/host
          method: post
          cors: true
  sendEmailByBookingInstantGuest:
    handler: src/functions/sendEmailByBookingInstantGuest.main
    events:
      - http:
          path: email/booking/{bookingId}/instant/guest
          method: post
          cors: true

resources:
  - ${file(src/resources/api-gateway-errors.yml)}
